# Generated by Django 3.2.10 on 2023-07-18 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='imgs',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='Фото'),
        ),
    ]
