# Generated by Django 4.2.3 on 2023-07-21 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_image_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['position']},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['pk']},
        ),
        migrations.AlterField(
            model_name='image',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='Позиция'),
        ),
    ]
